Trying to use the results from the automatic model find, but it complains: Also, the modules that are imported do not appear to have a "name" attribute, so is probably not properly initialised as scatteringModel.
Traceback (most recent call last):
  File "/Volumes/OrpheusB/brian/Code/mcsas/gui/modelwidget.py", line 117, in onDataSelected
    if cls is None or not issubclass(cls, dataobj.modelType):
  File "/Users/brian/.pyenv/versions/mcsas/lib/python2.7/abc.py", line 180, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/Users/brian/.pyenv/versions/mcsas/lib/python2.7/abc.py", line 184, in __subclasscheck__
    cls._abc_negative_cache.add(subclass)
  File "/Users/brian/.pyenv/versions/mcsas/lib/python2.7/_weakrefset.py", line 86, in add
    self.data.add(ref(item, self._remove))
TypeError: cannot create weak reference to 'module' object